services:
    _defaults:
        autowire: true
        autoconfigure: true

    Markocupic\SwissAlpineClubContaoLoginClientBundle\:
        resource: ../src/
        exclude: [
            ../src/{ DependencyInjection,Model,Session,Exception },
            ../src/Config/ContaoLogConfig.php,
            ../src/ErrorMessage/ErrorMessage.php,
            ../src/OAuth2/Client/OAuth2Client.php,
            ../src/OAuth2/Client/Provider/SwissAlpineClub.php,
            ../src/Security/Authenticator/Exception/*.php,
            ../src/Security/OAuth/OAuthUser.php,
            ../src/Security/User/ContaoUser.php,
        ]

    # Register session bags
    markocupic.sac_oauth2_client.session.factory:
        class: Markocupic\SwissAlpineClubContaoLoginClientBundle\Session\SessionFactory
        decorates: session.factory
        arguments:
            - '@markocupic.sac_oauth2_client.session.factory.inner'
            - '@markocupic.sac_oauth2_client.session.attribute.array_attribute_bag_backend'
            - '@markocupic.sac_oauth2_client.session.attribute.array_attribute_bag_frontend'

    markocupic.sac_oauth2_client.session.attribute.array_attribute_bag_backend:
        class: Markocupic\SwissAlpineClubContaoLoginClientBundle\Session\Attribute\ArrayAttributeBag
        arguments:
            - '_sac_oauth2_client_attr_backend'
        calls:
            - [ 'setName', [ 'sac_oauth2_client_attr_backend' ] ]

    markocupic.sac_oauth2_client.session.attribute.array_attribute_bag_frontend:
        class: Markocupic\SwissAlpineClubContaoLoginClientBundle\Session\Attribute\ArrayAttributeBag
        arguments:
            - '_sac_oauth2_client_attr_frontend'
        calls:
            - [ 'setName', [ 'sac_oauth2_client_attr_frontend' ] ]
