services:
    _defaults:
        autowire: true
        autoconfigure: true

    Markocupic\SwissAlpineClubContaoLoginClientBundle\:
        resource: ../src/
        exclude: [
            ../src/{ DependencyInjection,Model,Event,Session,Exception },
            ../src/Client/Provider/SwissAlpineClub.php,
            ../src/Client/OAuth2Client.php,
            ../src/Security/OAuth/OAuthUser.php,
            ../src/Config/ContaoLogConfig.php,
            ../src/ErrorMessage/ErrorMessage.php,
            ../src/Security/User/ContaoUser.php,
        ]

    Markocupic\SwissAlpineClubContaoLoginClientBundle\Controller\ContaoOAuth2LoginController:
        public: true
        arguments:
            - '@contao.framework'
            - '@contao.csrf.token_manager'
            - '@event_dispatcher'
            - '@Markocupic\SwissAlpineClubContaoLoginClientBundle\Client\OAuth2ClientFactory'
            - '%contao.csrf_token_name%'
            - '%sac_oauth2_client.oidc.enable_csrf_token_check%'

    Markocupic\SwissAlpineClubContaoLoginClientBundle\Controller\GetLogoutEndpointController:
        public: true
        arguments:
            - '%sac_oauth2_client.oidc.auth_provider_endpoint_logout%'

    Markocupic\SwissAlpineClubContaoLoginClientBundle\Client\Provider\ProviderFactory:
        arguments:
            - '@router.default'
            - # provider config
                'clientId': '%sac_oauth2_client.oidc.client_id%'
                'clientSecret': '%sac_oauth2_client.oidc.client_secret%'
                'urlAuthorize': '%sac_oauth2_client.oidc.auth_provider_endpoint_authorize%'
                'urlAccessToken': '%sac_oauth2_client.oidc.auth_provider_endpoint_token%'
                'urlResourceOwnerDetails': '%sac_oauth2_client.oidc.auth_provider_endpoint_userinfo%'
                'redirectRouteBackend': '%sac_oauth2_client.oidc.client_auth_endpoint_backend_route%'
                'redirectRouteFrontend': '%sac_oauth2_client.oidc.client_auth_endpoint_frontend_route%'

    Markocupic\SwissAlpineClubContaoLoginClientBundle\ErrorMessage\ErrorMessageManager:
        arguments:
            - '@request_stack'
            - '%sac_oauth2_client.session.flash_bag_key%'

    # Register session bags
    markocupic.sac_oauth2_client.session.factory:
        class: Markocupic\SwissAlpineClubContaoLoginClientBundle\Session\SessionFactory
        decorates: session.factory
        arguments:
            - '@markocupic.sac_oauth2_client.session.factory.inner'
            - '@markocupic.sac_oauth2_client.session.attribute.array_attribute_bag_backend'
            - '@markocupic.sac_oauth2_client.session.attribute.array_attribute_bag_frontend'

    markocupic.sac_oauth2_client.session.attribute.array_attribute_bag_backend:
        class: Markocupic\SwissAlpineClubContaoLoginClientBundle\Session\Attribute\ArrayAttributeBag
        arguments:
            - '_sac_oauth2_client_attr_backend'
        calls:
            - [ 'setName', [ 'sac_oauth2_client_attr_backend' ] ]

    markocupic.sac_oauth2_client.session.attribute.array_attribute_bag_frontend:
        class: Markocupic\SwissAlpineClubContaoLoginClientBundle\Session\Attribute\ArrayAttributeBag
        arguments:
            - '_sac_oauth2_client_attr_frontend'
        calls:
            - [ 'setName', [ 'sac_oauth2_client_attr_frontend' ] ]